"""Dossier refresh — bridge between a ``DossierDraft`` and the engineer crew.

Three pure functions plus one orchestration helper:

* :func:`target_path_for` — where the dossier lives in the target repo
  (``PROJECT_DOSSIER.md`` when ``manifest.dossier.publish`` is True; an
  internal path under ``data/dossiers/`` otherwise).
* :func:`build_dossier_engineer_output` — wraps a draft into the same
  ``EngineerOutput`` shape the engineer crew's ``output_override`` path
  consumes, so dossier PRs skip the LLM entirely.
* :func:`section_diff_summary` — produces a short, human-readable diff
  vs. the latest merged dossier for the Decision Record body.
* :func:`file_dossier_refresh_decision` — files the ``DOSSIER_REFRESH``
  Decision Record (``risk=low``) and submits it for operator approval.

The PR is opened by the existing ``scheduled/execute_approved`` sweep,
which detects ``DecisionType.DOSSIER_REFRESH`` and threads the override
through into ``run_engineer_crew``.
"""

from __future__ import annotations

from minions.approval.service import submit_for_approval
from minions.approval.store import DecisionStore
from minions.crews.engineer import EngineerOutput, FilePatch
from minions.dossiers.store_factory import DossierStoreLike
from minions.models.decision import Decision, DecisionType
from minions.models.dossier import DossierDraft, DossierSection, DossierStatus
from minions.models.manifest import Manifest
from minions.notify.base import Notifier

# Persisted as ``payload["dossier_draft_id"]`` on the Decision via Pydantic
# ``extra='allow'``. Constants give every callsite the same key.
DRAFT_ID_KEY = "dossier_draft_id"
TARGET_PATH_KEY = "dossier_target_path"
COMMIT_SHA_KEY = "dossier_commit_sha"


def target_path_for(manifest: Manifest) -> str:
    """Where to write ``PROJECT_DOSSIER.md`` inside the target repo.

    ``publish: false`` keeps the dossier outside the target repo entirely —
    it lives in the minions repo under ``data/dossiers/<project>.md``. In that
    case the engineer crew won't be invoked at all (different repo), so this
    function returns the in-minions path purely as a label for the Decision
    body; the actual write happens via a separate local writer (Phase 9).
    """
    if manifest.dossier.publish:
        return "PROJECT_DOSSIER.md"
    return f"data/dossiers/{manifest.name}.md"


def build_dossier_engineer_output(
    draft: DossierDraft, manifest: Manifest
) -> EngineerOutput:
    """Wrap the draft markdown in an ``EngineerOutput`` for the engineer crew.

    Always a single-file PR. ``operation="update"`` is fine for both
    create-and-update — the engineer crew normalizes this against the live
    target branch.
    """
    path = target_path_for(manifest)
    body_lines = [
        "Refresh `PROJECT_DOSSIER.md` for the project.",
        "",
        f"- Commit basis: `{draft.commit_sha[:12]}`",
        f"- Sections: {', '.join(s.value for s in draft.sections_present) or '(none)'}",
        f"- Crew: `{draft.crew_version}`",
        "",
        "_Auto-generated by the discoverer crew. Every claim cites "
        "`path:line` and was verified against the basis commit._",
    ]
    return EngineerOutput(
        pr_title=f"dossier: refresh PROJECT_DOSSIER.md ({draft.commit_sha[:8]})",
        pr_body="\n".join(body_lines),
        files=[
            FilePatch(
                path=path,
                content=draft.markdown,
                operation="update",
            )
        ],
    )


def section_diff_summary(
    new: DossierDraft, prior: DossierDraft | None
) -> str:
    """Short, human-readable diff of section coverage for the Decision body."""
    new_sections = set(new.sections_present)
    if prior is None:
        return (
            "First dossier on record for this project. "
            f"Sections present: {', '.join(s.value for s in new.sections_present) or '(none)'}."
        )
    prior_sections = set(prior.sections_present)
    added = sorted(s.value for s in new_sections - prior_sections)
    removed = sorted(s.value for s in prior_sections - new_sections)
    parts: list[str] = []
    if added:
        parts.append(f"sections added: {', '.join(added)}")
    if removed:
        parts.append(f"sections removed: {', '.join(removed)}")
    parts.append(f"commit basis: {prior.commit_sha[:8]} → {new.commit_sha[:8]}")
    return "; ".join(parts) or "no structural changes (body may still differ)"


def find_open_refresh_decision(
    *, project: str, decision_store: DecisionStore
) -> Decision | None:
    """Return the existing pending/approved DOSSIER_REFRESH for this project, if any.

    Dedupe guard: an operator who runs ``minions discover <p> --no-dry-run``
    twice in a row (or a cron tick that re-fires before the first decision
    is resolved) should not produce two separate refresh decisions for the
    same project. Once a decision is EXECUTED (PR opened) or REJECTED, a new
    discovery run IS allowed to file a fresh one.
    """
    from minions.models.decision import DecisionStatus

    open_statuses = (DecisionStatus.PENDING, DecisionStatus.APPROVED)
    for d in decision_store.list_all():
        if d.project != project:
            continue
        if d.type != DecisionType.DOSSIER_REFRESH:
            continue
        if d.status in open_statuses:
            return d
    return None


def file_dossier_refresh_decision(
    *,
    draft: DossierDraft,
    manifest: Manifest,
    decision_store: DecisionStore,
    dossier_store: DossierStoreLike,
    notifier: Notifier,
) -> Decision:
    """Create + submit a ``DOSSIER_REFRESH`` Decision for the given draft.

    Idempotent per project: if a pending or approved DOSSIER_REFRESH already
    exists for ``manifest.name`` it is returned unchanged (no new Decision
    filed, no notifier ping). Lets the operator re-run discovery without
    flooding the approval queue.

    The Decision body summarises the section diff vs the last merged dossier;
    the ``dossier_draft_id`` / ``dossier_target_path`` / ``dossier_commit_sha``
    fields ride along on the Decision payload via Pydantic ``extra='allow'``
    so the execute-approved sweep can reconstruct the override later.
    """
    existing = find_open_refresh_decision(
        project=manifest.name, decision_store=decision_store,
    )
    if existing is not None:
        return existing

    prior = dossier_store.latest_merged(manifest.name)
    summary = (
        f"dossier: refresh PROJECT_DOSSIER.md "
        f"({draft.commit_sha[:8]}) for {manifest.name}"
    )
    rationale = (
        "Discoverer crew produced a fresh PROJECT_DOSSIER.md. "
        "Approving opens a draft PR against the target repo. "
        f"Diff vs prior: {section_diff_summary(draft, prior)}."
    )
    body_lines = [
        "## Dossier refresh",
        "",
        f"- Project: `{manifest.name}`",
        f"- Target path: `{target_path_for(manifest)}`",
        f"- Commit basis: `{draft.commit_sha}`",
        f"- Crew version: `{draft.crew_version}`",
        f"- Sections present: "
        f"{', '.join(s.value for s in draft.sections_present) or '(none)'}",
        "",
        "### Verifier",
        "```",
        (draft.verifier_log or "(no log recorded)").strip(),
        "```",
    ]
    decision = Decision(
        project=manifest.name,
        type=DecisionType.DOSSIER_REFRESH,
        risk="low",
        summary=summary,
        rationale=rationale,
        diff_or_plan="\n".join(body_lines),
        proposer_role="cloud_devops",
        proposer_agent_id=f"discoverer@{manifest.name}",
        requested_by_role="discoverer",
    )
    # Pydantic ``extra='allow'`` carries these through to the persisted
    # payload. The execute-approved sweep reads them off ``model_extra``.
    decision.__pydantic_extra__ = {
        DRAFT_ID_KEY: str(draft.id),
        TARGET_PATH_KEY: target_path_for(manifest),
        COMMIT_SHA_KEY: draft.commit_sha,
    }
    submit_for_approval(decision, store=decision_store, notifier=notifier)
    return decision


def is_dossier_refresh_decision(decision: Decision) -> bool:
    return decision.type == DecisionType.DOSSIER_REFRESH


def draft_id_from_decision(decision: Decision) -> str | None:
    extra = getattr(decision, "model_extra", None) or {}
    raw = extra.get(DRAFT_ID_KEY)
    return str(raw) if raw else None


def _ensure_status(draft: DossierDraft, status: DossierStatus) -> DossierDraft:
    draft.status = status
    return draft


__all__ = [
    "COMMIT_SHA_KEY",
    "DRAFT_ID_KEY",
    "find_open_refresh_decision",
    "TARGET_PATH_KEY",
    "build_dossier_engineer_output",
    "draft_id_from_decision",
    "file_dossier_refresh_decision",
    "is_dossier_refresh_decision",
    "section_diff_summary",
    "target_path_for",
    # Re-export so callers can satisfy mypy without reaching past us.
    "DossierSection",
]
